title: Secure Sight Mobile Surveillance
description: Solar-powered mobile security trailers for construction and events.
url: "https://securesightut.com"


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  posts:
    output: true